server:
  port: ${PORT_API_GATEWAY:9090}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: clientes
              uri: lb://msvc-cliente
              predicates:
                - Path=/api/cliente/**
            - id: socios
              uri: lb://msvc-man-socio
              predicates:
                - Path=/api/socio/**
            - id: historial
              uri: lb://msvc-historial
              predicates:
                - Path=//api/historial/socio/**
    loadbalancer:
      configurations: default