server:
  port: ${PORT_CLIENT_KEYCLO:9099}

spring:
  security:
    oauth2:
      client:
        provider:
          cjava-realm:
            issuer-uri: http://keycloak.local:8080/realms/cjava-realm
        registration:
          cjava-realm:
            provider: cjava-realm
            client-name: Cjava Client de keycloak
            client-id: cjava-client
            client-secret: E433SCWrlQXLWj9ibM8pdew1cQfT7p3S
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9099/login/oauth2/code/cjava-realm

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
