server:
  port: ${PORT_SERVICE_CLIENTE}

spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_CONF_URI}
      profile: ${CONFIG_SERVER_PROFILE}
      enabled: true

  datasource:
    url: ${BD_MYSQL_URL}
    username: ${BD_MYSQL_USERNAME}
    password: ${BD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQLDialect
         format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
